---
title: "NASDAQ-100 Project 1"
author: "Hang Liao"
output: 
  html_document:
    toc: true
    # toc_depth: 1
    toc_float: true
    number_sections: true
    
date: "`r Sys.Date()`"


---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gapminder)
library(dplyr)
library(ggplot2)
library(xlsx)
```

## Obtain NASDAQ-100 Constituent List


```{r NASDAQ-100-constituent-list}
NASDAQ_100 <- read.csv("First.csv")
###Constituent_list
NASDAQ_100 <- NASDAQ_100 %>% 
  filter(conm == "Nasdaq 100", is.na(thru) | thru > 20220101 )

###Form in 2021
NASDAQ_100_2021 <- NASDAQ_100 %>% 
  filter(from > 20210101 )
count(NASDAQ_100_2021)
### There are 8 stocks are constituents only part of 2021
```

## ID Cross-walk
```{r ID-Cross-walk}
#upload ID cross-walk
ID_cross_walk <- read.csv("ID cross-walk.csv")

```


## Daily Stock Price Data for the Constituents
```{r daily-stock-price}
###upload Daily Stock Price
Daily_Stock_Price <- read.csv("Daily Stock Price.csv")

###Calculate the Market cap as weight
Daily_Stock_Price$MARKETSHARE =  Daily_Stock_Price$PRC * Daily_Stock_Price$SHROUT

Daily_Data <- group_by(Daily_Stock_Price, date)
Daily_Avg <- summarise(Daily_Data,
                       weighted_return = weighted.mean(RET,MARKETSHARE))

###transfer the date from character to Date
Daily_Avg <- Daily_Avg %>%
  mutate(date = as.Date(as.character(date), format = "%Y %m %d"))


```

## OUTPUT Plots

```{r weighted-average-of-daily-return-plot,fig.cap = 'Figure 1.1 The Weighted Average of Daily Return of All Constituent Stock in 2021'}
ggplot(Daily_Avg , aes(x =date, y = weighted_return)) +
  geom_line() +
  scale_y_continuous(
    limits = c(-0.04,0.04),
    breaks = seq(-0.04,0.04,0.01)) +
  geom_hline(yintercept = 0) +
labs(
  title = "Weighted Average of Daily Return",
  x = "Date",
  y = "Weighted Return"
)

```


## NASDAQ 100 from YaHoo and Plot
```{r Official-NASDAQ-100, fig.cap = 'Figure 1.2 Official_NASDAQ_100 in 2021 from YaHoo'}
###upload Official-NASDAQ-100
Official_NASDAQ_100 <- read.csv("^NDX.csv")


###transfer the date from character to Date
Official_NASDAQ_100 <- Official_NASDAQ_100 %>%
  mutate(Date = as.Date(Date), format = "%Y %m %d")

###Calculate the daily return using open price and close price
Official_NASDAQ_100$Daily_Return <-
  ((Official_NASDAQ_100$Close-Official_NASDAQ_100$Open)/Official_NASDAQ_100$Open)


ggplot(Official_NASDAQ_100 , aes(x = Date, y = Daily_Return)) +
  geom_line() +
  scale_y_continuous(
    limits = c(-0.03,0.03),
    breaks = seq(-0.03,0.03,0.01)) +
  geom_hline(yintercept = 0) +
  labs(
    title = "Official_NASDAQ_100",
    x = "Date",
    y = "Daily_Return"
  )
```
### The plot I got from all constituent stock is similiar to the plot generated by the data from Yahoo. 
### They have a basically same trend 

  
